theme: jekyll-theme-minimal

github:
  is_project_page: false

title: Yuan Meng's Home Page
description: This is Yuan Meng. Welcome to my personal territory.

logo: https://github.com/CatherineMeng/main-page/blob/master/pics/IMG_0720.jpg
